name: Deploy

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@2
    - uses: actions/setup@v1
    - run: npm ci
    - run: npm run build